/:
    path: /
    controller: App\Controller\ImagesController::Doudounes

Doudounes:
    path: /Doudounes
    controller: App\Controller\ImagesController::Doudounes

FursWomen:
    path: /Furs/Women
    controller: App\Controller\ImagesController::fursWomen

FursMen:
    path: /Furs/Men
    controller: App\Controller\ImagesController::fursMen

Pulls:
    path: /Pulls/Pulls
    controller: App\Controller\ImagesController::Pulls

Creapulka:
    path: /Pull/Creapulka
    controller: App\Controller\ImagesController::Creapulka

Delicious_Sev:
    path: /Pull/Delicious_Sev
    controller: App\Controller\ImagesController::Delicious_Sev




Wax:
    path: /Wax
    controller: App\Controller\ImagesController::Wax




#ExploWax:
#    path: /Wax/Explo
#    controller: App\Controller\ImagesController::exploWax

#ExploDoudounes:
#    path: /Doudounes/Explo
#    controller: App\Controller\ImagesController::exploDoudounes





pullsDownload:
    path: /Pulls/Pulls/download
    controller: App\Controller\DownloadController::downloadPulls

pullsUpload:
    path: /Pulls/Pulls/upload
    controller: App\Controller\DownloadController::uploadPulls
    methods: [POST]

creapulkaDownload:
    path: /Pulls/Creapulka/download
    controller: App\Controller\DownloadController::downloadCreapulka


creapulkaUpload:
    path: /Pulls/Creapulka/upload
    controller: App\Controller\DownloadController::uploadCreapulka
    methods: [POST]

delicious_SevUpload:
    path: /Pulls/Delicious_Sev/upload
    controller: App\Controller\DownloadController::uploadDelicious_Sev
    methods: [POST]

delicious_SevDownload:
    path: /Pulls/Delicious_Sev/download
    controller: App\Controller\DownloadController::downloadDelicious_Sev

fursDownloadWomen:
    path: /Furs/Women/download
    controller: App\Controller\DownloadController::downloadFursWomen

fursDownloadMen:
    path: /Furs/Men/download
    controller: App\Controller\DownloadController::downloadFursMen

fursUploadWomen:
    path: /Furs/Women/upload
    controller: App\Controller\DownloadController::uploadFursWomen
    methods: [POST]

fursUploadMen:
    path: /Furs/Men/upload
    controller: App\Controller\DownloadController::uploadFursMen
    methods: [POST]

doudounesDownload:
    path: /Doudounes/download
    controller: App\Controller\DownloadController::downloadDoudounes

doudounesUpload:
    path: /Doudounes/upload
    controller: App\Controller\DownloadController::uploadDoudounes
    methods: [POST]

waxDownload:
    path: /Wax/download
    controller: App\Controller\DownloadController::downloadWax

waxUpload:
    path: /Wax/upload
    controller: App\Controller\DownloadController::uploadWax
    methods: [POST]


UpdateFursWomen:
    path: /Furs/Women/Update
    controller: App\Controller\DownloadController::updateFurWomen

UpdateFursMen:
    path: /Furs/Men/Update
    controller: App\Controller\DownloadController::updateFurMen


UpdateDoudounes:
    path: /Doudounes/Update
    controller: App\Controller\DownloadController::updateDoudounes


UpdatePulls:
    path: /Pulls/Pulls/Update
    controller: App\Controller\DownloadController::updatePulls

UpdateCreapulka:
    path: /Pulls/Creapulka/Update
    controller: App\Controller\DownloadController::updateCreapulka

UpdateDelicious_Sev:
    path: /Pulls/Delicious_Sev/Update
    controller: App\Controller\DownloadController::updateDelicious_Sev


UpdateWax:
    path: /Pulls/Wax/Update
    controller: App\Controller\DownloadController::updateWax


cropButton:
    path: /cropButton
    controller: App\Controller\DownloadController::cropButton


#ListDoudounes:
#     path: /Doudounes/Delete
#     controller: App\Controller\DownloadController::listDoudounes

#ListFurWomen:
#     path: /Furs/Women/Delete
#     controller: App\Controller\DownloadController::listFursWomen

EraseDoudounes:
     path: /Doudounes/Delete/{id}/{images_id}
     controller: App\Controller\DownloadController::eraseModalDoudoune
     methods: [GET]

EraseWax:
     path: /Wax/Delete/{id}/{images_id}
     controller: App\Controller\DownloadController::eraseModalWax
     methods: [GET]

ErasePulls:
     path: /Pulls/Delete/{id}/{images_id}
     controller: App\Controller\DownloadController::eraseModalPulls
     methods: [GET]

EraseCreapulka:
     path: /Pulls/Creapulka/Delete/{id}/{images_id}
     controller: App\Controller\DownloadController::eraseModalCreapulka
     methods: [GET]

EraseDelicious_Sev:
     path: /Pulls/Delicious_Sev/Delete/{id}/{images_id}
     controller: App\Controller\DownloadController::eraseModalDelicious_Sev
     methods: [GET]

EraseFursWomen:
     path: /Furs/Women/Delete/{id}/{images_id}
     controller: App\Controller\DownloadController::eraseModalFursWomen
     methods: [GET]

EraseFursMen:
     path: /Furs/Men/Delete/{id}/{images_id}
     controller: App\Controller\DownloadController::eraseModalFursMen
     methods: [GET]

DestroyDoudoune:
      path: /Doudounes/Delete/destroy/{id}/{images_id}
      controller: App\Controller\DownloadController::destroyDoudoune

DestroyWax:
      path: /Wax/Delete/destroy/{id}/{images_id}
      controller: App\Controller\DownloadController::destroyWax

DestroyPulls:
      path: /Pulls/Delete/destroy/{id}/{images_id}
      controller: App\Controller\DownloadController::destroyPulls

DestroyCreapulka:
      path: /Pulls/Creapulka/Delete/destroy/{id}/{images_id}
      controller: App\Controller\DownloadController::destroyCreapulka

DestroyDelicious_Sev:
      path: /Pulls/Delicious_Sev/Delete/destroy/{id}/{images_id}
      controller: App\Controller\DownloadController::destroyDelicious_Sev

DestroyFursWomen:
      path: /Furs/Women/Delete/destroy/{id}/{images_id}
      controller: App\Controller\DownloadController::destroyFursWomen

DestroyFursMen:
      path: /Furs/Men/Delete/destroy/{id}/{images_id}
      controller: App\Controller\DownloadController::destroyFursMen

