#affichages des thèmes


/:
    path: /
    controller: App\Controller\ImagesController::Doudounes

Doudounes:
    path: /Doudounes/Doudounes
    controller: App\Controller\ImagesController::Doudounes

Desigual:
    path: /Doudounes/Desigual
    controller: App\Controller\ImagesController::Desigual

FursWomen:
    path: /Furs/Women
    controller: App\Controller\ImagesController::fursWomen

FursMen:
    path: /Furs/Men
    controller: App\Controller\ImagesController::fursMen

Pulls:
    path: /Pulls/Pulls
    controller: App\Controller\ImagesController::Pulls

Creapulka:
    path: /Pulls/Creapulka
    controller: App\Controller\ImagesController::Creapulka

Delicious_Sev:
    path: /Pulls/Delicious_Sev
    controller: App\Controller\ImagesController::Delicious_Sev

Wax:
    path: /Wax
    controller: App\Controller\ImagesController::Wax


#Update

UpdateDoudounes:
    path: /Doudounes/Doudounes/Update
    controller: App\Controller\DownloadController::updateDoudounes

UpdateDesigual:
    path: /Doudounes/Desigual/Update
    controller: App\Controller\DownloadController::updateDesigual


UpdateFursWomen:
    path: /Furs/Women/Update
    controller: App\Controller\DownloadController::updateFurWomen

UpdateFursMen:
    path: /Furs/Men/Update
    controller: App\Controller\DownloadController::updateFurMen

UpdatePulls:
    path: /Pulls/Pulls/Update
    controller: App\Controller\DownloadController::updatePulls

UpdateCreapulka:
    path: /Pulls/Creapulka/Update
    controller: App\Controller\DownloadController::updateCreapulka

UpdateDelicious_Sev:
    path: /Pulls/Delicious_Sev/Update
    controller: App\Controller\DownloadController::updateDelicious_Sev

UpdateWax:
    path: /Wax/Update
    controller: App\Controller\DownloadController::updateWax

# Erase


EraseDoudounes:
     path: /Doudounes/Doudounes/Delete/{basename}/{id}/{images_id}
     controller: App\Controller\DownloadController::eraseModalDoudoune
     methods: [GET]

EraseDesigual:
     path: /Doudounes/Desigual/Delete/{basename}/{id}/{images_id}
     controller: App\Controller\DownloadController::eraseModalDesigual
     methods: [GET]

EraseWax:
     path: /Wax/Delete/{basename}/{id}/{images_id}
     controller: App\Controller\DownloadController::eraseModalWax
     methods: [GET]

ErasePulls:
     path: /Pulls/Pulls/Delete/{basename}/{id}/{images_id}
     controller: App\Controller\DownloadController::eraseModalPulls
     methods: [GET]

EraseCreapulka:
     path: /Pulls/Creapulka/Delete/{basename}/{id}/{images_id}
     controller: App\Controller\DownloadController::eraseModalCreapulka
     methods: [GET]

EraseDelicious_Sev:
     path: /Pulls/Delicious_Sev/Delete/{basename}/{id}/{images_id}
     controller: App\Controller\DownloadController::eraseModalDelicious_Sev
     methods: [GET]

EraseFursWomen:
     path: /Furs/Women/Delete/{basename}/{id}/{images_id}
     controller: App\Controller\DownloadController::eraseModalFursWomen
     methods: [GET]

EraseFursMen:
     path: /Furs/Men/Delete/{basename}/{id}/{images_id}
     controller: App\Controller\DownloadController::eraseModalFursMen
     methods: [GET]

#eraseAll

EraseDoudounesAll:
  path: /Doudounes/Doudounes/Delete/All/EraseDoudounesAll
  controller: App\Controller\DownloadController::eraseModalDoudounesAll
  methods: [GET]

EraseDesigualAll:
  path: /Doudounes/Desigual/Delete/All/EraseDesigualAll
  controller: App\Controller\DownloadController::eraseModalDesigualAll
  methods: [GET]

EraseFursWomenAll:
  path: /Furs/Women/Delete/All/EraseFursWomenAll
  controller: App\Controller\DownloadController::eraseModalFursWomenAll
  methods: [GET]

EraseFursMenAll:
  path: /Furs/Men/Delete/All/EraseFursMenAll
  controller: App\Controller\DownloadController::eraseModalFursMenAll
  methods: [GET]

ErasePullsAll:
  path: /Pulls/Pulls/Delete/All/ErasePullsAll
  controller: App\Controller\DownloadController::eraseModalPullsAll
  methods: [GET]

EraseCreapulkaAll:
  path: /Pulls/Creapulka/Delete/All/EraseCreapulkaAll
  controller: App\Controller\DownloadController::eraseModalCreapulkaAll
  methods: [GET]

EraseDelicious_SevAll:
  path: /Pulls/Delicious_Sev/Delete/All/EraseDelicious_SevAll
  controller: App\Controller\DownloadController::eraseModalDelicious_SevAll
  methods: [GET]

EraseWaxAll:
  path: /Wax/Delete/All/EraseWaxAll
  controller: App\Controller\DownloadController::eraseModalWaxAll
  methods: [GET]






#destroy

DestroyDoudoune:
      path: /Doudounes/Doudounes/Delete/destroy/{basename}/{id}/{images_id}
      controller: App\Controller\DownloadController::destroyDoudoune

DestroyDesigual:
      path: /Doudounes/Desigual/Delete/destroy/{basename}/{id}/{images_id}
      controller: App\Controller\DownloadController::destroyDesigual

DestroyWax:
      path: /Wax/Delete/destroy/{basename}/{id}/{images_id}
      controller: App\Controller\DownloadController::destroyWax

DestroyPulls:
      path: /Pulls/Delete/destroy/{basename}/{id}/{images_id}
      controller: App\Controller\DownloadController::destroyPulls

DestroyCreapulka:
      path: /Pulls/Creapulka/Delete/destroy/{basename}/{id}/{images_id}
      controller: App\Controller\DownloadController::destroyCreapulka

DestroyDelicious_Sev:
      path: /Pulls/Delicious_Sev/Delete/destroy/{basename}/{id}/{images_id}
      controller: App\Controller\DownloadController::destroyDelicious_Sev

DestroyFursWomen:
      path: /Furs/Women/Delete/destroy/{basename}/{id}/{images_id}
      controller: App\Controller\DownloadController::destroyFursWomen

DestroyFursMen:
      path: /Furs/Men/Delete/destroy/{basename}/{id}/{images_id}
      controller: App\Controller\DownloadController::destroyFursMen

#destroyAll

DestroyDoudounesAll:
  path: /Doudounes/Doudounes/Delete/destroy/All
  controller: App\Controller\DownloadController::destroyDoudounesAll

DestroyDesigualAll:
  path: /Doudounes/Desigual/Delete/destroy/All
  controller: App\Controller\DownloadController::destroyDesigualAll

DestroyFursWomenAll:
  path: /Furs/Women/Delete/destroy/All
  controller: App\Controller\DownloadController::destroyFursWomenAll

DestroyFursMenAll:
  path: /Furs/Men/Delete/destroy/All
  controller: App\Controller\DownloadController::destroyFursMenAll

DestroyPullsAll:
  path: /Pulls/Pulls/Delete/destroy/All
  controller: App\Controller\DownloadController::destroyPullsAll

DestroyCreapulkaAll:
  path: /Pulls/Creapulka/Delete/destroy/All
  controller: App\Controller\DownloadController::destroyCreapulkaAll

DestroyDelicious_SevAll:
  path: /Pulls/Delicious_Sev/Delete/destroy/All
  controller: App\Controller\DownloadController::destroyDelicious_SevAll

DestroyWaxAll:
  path: /Wax/Delete/destroy/All
  controller: App\Controller\DownloadController::destroyWaxAll