#affichages des thèmes


/:
    path: /
    controller: App\Controller\ImagesController::Doudounes

Doudounes:
    path: /Doudounes
    controller: App\Controller\ImagesController::Doudounes

FursWomen:
    path: /Furs/Women
    controller: App\Controller\ImagesController::fursWomen

FursMen:
    path: /Furs/Men
    controller: App\Controller\ImagesController::fursMen

Pulls:
    path: /Pulls/Pulls
    controller: App\Controller\ImagesController::Pulls

Creapulka:
    path: /Pull/Creapulka
    controller: App\Controller\ImagesController::Creapulka

Delicious_Sev:
    path: /Pull/Delicious_Sev
    controller: App\Controller\ImagesController::Delicious_Sev

Wax:
    path: /Wax
    controller: App\Controller\ImagesController::Wax


#Update

UpdateDoudounes:
    path: /Doudounes/Update
    controller: App\Controller\DownloadController::updateDoudounes


UpdateFursWomen:
    path: /Furs/Women/Update
    controller: App\Controller\DownloadController::updateFurWomen

UpdateFursMen:
    path: /Furs/Men/Update
    controller: App\Controller\DownloadController::updateFurMen

UpdatePulls:
    path: /Pulls/Pulls/Update
    controller: App\Controller\DownloadController::updatePulls

UpdateCreapulka:
    path: /Pulls/Creapulka/Update
    controller: App\Controller\DownloadController::updateCreapulka

UpdateDelicious_Sev:
    path: /Pulls/Delicious_Sev/Update
    controller: App\Controller\DownloadController::updateDelicious_Sev

UpdateWax:
    path: /Pulls/Wax/Update
    controller: App\Controller\DownloadController::updateWax

# Erase


EraseDoudounes:
     path: /Doudounes/Delete/{basename}/{id}/{images_id}
     controller: App\Controller\DownloadController::eraseModalDoudoune
     methods: [GET]

EraseWax:
     path: /Wax/Delete/{basename}/{id}/{images_id}
     controller: App\Controller\DownloadController::eraseModalWax
     methods: [GET]

ErasePulls:
     path: /Pulls/Delete/{basename}/{id}/{images_id}
     controller: App\Controller\DownloadController::eraseModalPulls
     methods: [GET]

EraseCreapulka:
     path: /Pulls/Creapulka/Delete/{basename}/{id}/{images_id}
     controller: App\Controller\DownloadController::eraseModalCreapulka
     methods: [GET]

EraseDelicious_Sev:
     path: /Pulls/Delicious_Sev/Delete/{basename}/{id}/{images_id}
     controller: App\Controller\DownloadController::eraseModalDelicious_Sev
     methods: [GET]

EraseFursWomen:
     path: /Furs/Women/Delete/{basename}/{id}/{images_id}
     controller: App\Controller\DownloadController::eraseModalFursWomen
     methods: [GET]

EraseFursMen:
     path: /Furs/Men/Delete/{basename}/{id}/{images_id}
     controller: App\Controller\DownloadController::eraseModalFursMen
     methods: [GET]

#eraseAll

EraseDoudounesAll:
  path: /Doudounes/Delete/All/EraseDoudounesAll
  controller: App\Controller\DownloadController::eraseModalDoudounesAll
  methods: [GET]

EraseFursWomenAll:
  path: /Furs/Women/Delete/All/EraseFursWomenAll
  controller: App\Controller\DownloadController::eraseModalFursWomenAll
  methods: [GET]






#destroy

DestroyDoudoune:
      path: /Doudounes/Delete/destroy/{basename}/{id}/{images_id}
      controller: App\Controller\DownloadController::destroyDoudoune

DestroyWax:
      path: /Wax/Delete/destroy/{basename}/{id}/{images_id}
      controller: App\Controller\DownloadController::destroyWax

DestroyPulls:
      path: /Pulls/Delete/destroy/{basename}/{id}/{images_id}
      controller: App\Controller\DownloadController::destroyPulls

DestroyCreapulka:
      path: /Pulls/Creapulka/Delete/destroy/{basename}/{id}/{images_id}
      controller: App\Controller\DownloadController::destroyCreapulka

DestroyDelicious_Sev:
      path: /Pulls/Delicious_Sev/Delete/destroy/{basename}/{id}/{images_id}
      controller: App\Controller\DownloadController::destroyDelicious_Sev

DestroyFursWomen:
      path: /Furs/Women/Delete/destroy/{basename}/{id}/{images_id}
      controller: App\Controller\DownloadController::destroyFursWomen

DestroyFursMen:
      path: /Furs/Men/Delete/destroy/{basename}/{id}/{images_id}
      controller: App\Controller\DownloadController::destroyFursMen

#destroyAll

DestroyDoudounesAll:
  path: /Doudounes/Delete/destroy/All
  controller: App\Controller\DownloadController::destroyDoudounesAll

DestroyFursWomenAll:
  path: /Furs/Women/Delete/destroy/All
  controller: App\Controller\DownloadController::destroyFursWomenAll